# Generated by Django 5.2.17 on 2026-10-02 19:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identificador')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='hash do token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('expires_at', models.DateTimeField(verbose_name='data de expiração')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='último acesso')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='data de revogação')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'sessão',
                'verbose_name_plural': 'sessões',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='session_user_active_idx'), models.Index(fields=['expires_at'], name='accounts_session_expires_idx')],
            },
        ),
    ]
