# Generated by Django 5.2.17 on 2026-10-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_session'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user',), name='session_one_active_per_user'),
        ),
    ]
