# Generated by Django 5.2.17 on 2026-10-03 21:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_session_session_one_active_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='identificador')),
                ('challenge_type', models.CharField(choices=[('EMAIL_OTP', 'Código por e-mail')], max_length=32, verbose_name='tipo')),
                ('token_hash', models.CharField(max_length=64, verbose_name='hash do código')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
                ('expires_at', models.DateTimeField(verbose_name='data de expiração')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='data de validação')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='data de revogação')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentativas')),
                ('max_attempts', models.PositiveSmallIntegerField(default=5, verbose_name='máximo de tentativas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authentication_challenges', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'desafio de autenticação',
                'verbose_name_plural': 'desafios de autenticação',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='challenge_user_active_idx'), models.Index(fields=['expires_at'], name='challenge_expires_idx')],
            },
        ),
    ]
