# Generated by Django 5.2.17 on 2026-10-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_authenticationchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticationchallenge',
            name='consumed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data de consumo'),
        ),
    ]
