# Generated by Django 5.2.17 on 2026-10-05 14:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JwtSigningKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kid', models.CharField(max_length=100, unique=True, verbose_name='identificador da chave')),
                ('algorithm', models.CharField(default='EdDSA', max_length=20, verbose_name='algoritmo')),
                ('private_key', models.TextField(verbose_name='chave privada criptografada')),
                ('public_key', models.TextField(verbose_name='chave pública')),
                ('enabled', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('retired_at', models.DateTimeField(blank=True, null=True, verbose_name='aposentada em')),
            ],
            options={
                'verbose_name': 'chave de assinatura JWT',
                'verbose_name_plural': 'chaves de assinatura JWT',
                'ordering': ('-created_at',),
            },
        ),
    ]
