# Generated by Django 5.2.17 on 2026-10-07 18:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('service', models.CharField(help_text='Identificador do serviço que utilizará esta credencial.', max_length=100, verbose_name='serviço')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='hash do token')),
                ('enabled', models.BooleanField(default=True, verbose_name='ativa')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='último uso')),
            ],
            options={
                'verbose_name': 'credencial de serviço',
                'verbose_name_plural': 'credenciais de serviço',
                'ordering': ('service', 'name'),
                'constraints': [models.UniqueConstraint(fields=('service', 'name'), name='uq_service_credential_service_name')],
            },
        ),
    ]
