# Generated by Django 5.2.17 on 2026-10-09 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_service_alter_servicecredential_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jwtsigningkey',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='servicecredential',
            options={'ordering': ['service', 'name']},
        ),
        migrations.AlterField(
            model_name='jwtsigningkey',
            name='algorithm',
            field=models.CharField(choices=[('EdDSA', 'EdDSA')], default='EdDSA', max_length=20),
        ),
        migrations.AlterField(
            model_name='jwtsigningkey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jwtsigningkey',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jwtsigningkey',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jwtsigningkey',
            name='kid',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='jwtsigningkey',
            name='private_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jwtsigningkey',
            name='public_key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jwtsigningkey',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicecredential',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicecredential',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='servicecredential',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecredential',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicecredential',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicecredential',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='servicecredential',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='security.service'),
        ),
        migrations.AlterField(
            model_name='servicecredential',
            name='token_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='TechnicalEndpoint',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['path', 'http_method'],
                'constraints': [models.UniqueConstraint(fields=('http_method', 'path'), name='uq_technical_endpoint_method_path')],
            },
        ),
        migrations.CreateModel(
            name='ServiceTechnicalEndpoint',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_endpoints', to='security.service')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_services', to='security.technicalendpoint')),
            ],
            options={
                'ordering': ['service', 'endpoint'],
                'constraints': [models.UniqueConstraint(fields=('service', 'endpoint'), name='uq_service_technical_endpoint')],
            },
        ),
    ]
