# Generated by Django 5.2.17 on 2026-10-04 23:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('integration_type', models.CharField(choices=[('REST_API', 'API REST')], default='REST_API', max_length=30, verbose_name='tipo')),
                ('base_url', models.URLField(max_length=500, verbose_name='URL base')),
                ('enabled', models.BooleanField(default=True, verbose_name='ativa')),
                ('timeout', models.PositiveIntegerField(default=10, help_text='Tempo máximo da requisição em segundos.', verbose_name='timeout')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
            ],
            options={
                'verbose_name': 'integração',
                'verbose_name_plural': 'integrações',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('credential_type', models.CharField(choices=[('API_KEY', 'API Key'), ('BEARER_TOKEN', 'Bearer Token'), ('BASIC_AUTH', 'Basic Auth'), ('OAUTH2', 'OAuth 2.0')], max_length=30, verbose_name='tipo')),
                ('encrypted_value', models.TextField(verbose_name='valor criptografado')),
                ('enabled', models.BooleanField(default=True, verbose_name='ativa')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='integrations.integration', verbose_name='integração')),
            ],
            options={
                'verbose_name': 'credencial de integração',
                'verbose_name_plural': 'credenciais de integração',
                'ordering': ('integration', 'name'),
            },
        ),
    ]
