# Generated by Django 5.2.17 on 2026-10-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationcredential',
            name='fingerprint',
            field=models.CharField(blank=True, help_text='Identificador SHA-256 da credencial.', max_length=64, null=True, unique=True, verbose_name='fingerprint'),
        ),
    ]
